# -*- coding: utf-8 -*-
"""ecoli_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ivuuSDChmpUPnr2ecdU003aMzHaW15D

# E. coli / Not E. coli / Uncertain — прототип (Colab)

Запускайте ячейки СВЕРХУ ВНИЗ, по одной. Перед началом: Среда выполнения → Сменить тип среды → T4 GPU.

Перед ячейкой 2 в Colab должен быть доступен набор *Multi-Organism Bacterial Imaging Dataset* (см. комментарий в ячейке 2).
"""

# ЯЧЕЙКА 1. Установка и импорты (запустить один раз)
!pip install -q gradio scikit-learn kagglehub

import random, json, shutil, warnings
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from IPython.display import display

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms as T

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (accuracy_score, average_precision_score, balanced_accuracy_score,
                             confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score)
from sklearn.model_selection import StratifiedGroupKFold, cross_val_predict

warnings.filterwarnings("ignore")

SEED = 42


def set_seed(s):
    random.seed(s)
    np.random.seed(s)
    torch.manual_seed(s)
    torch.cuda.manual_seed_all(s)


set_seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Устройство:", DEVICE, "(для ускорения: Среда выполнения -> Сменить тип -> T4 GPU, но ДО загрузки данных)")

# ЯЧЕЙКА 2. Настройки и сбор таблицы с картинками (DataFrame)
IMG_SIZE = 320          # все картинки приводятся к 320x320
USE_PRETRAINED = True   # веса ImageNet (скачаются сами)
DUP_THRESH = 6          # порог «почти-дубликата» (расстояние Хэмминга из 64 бит)
EXT = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
POSITIVE_KEYS = ["escherichia", "e.coli", "e. coli", "e_coli", "ecoli"]  # признак класса E. coli в названии папки
EXCLUDE_KEYS = ["media plate"]                                          # папки с чашками Петри выбрасываем

# Источник 1: Multi-Organism Bacterial Imaging Dataset (папки '<вид>_gram stain' и '<вид>_media plate')
import kagglehub

# Download latest version
MULTI_PATH = kagglehub.dataset_download("ujjwalsinha01/multi-organism-bacterial-imaging-dataset")
print("Path to dataset files:", MULTI_PATH)
# Источник 2: DIBaS (окраска по Граму, микроскопия)
import kagglehub
DIBAS_PATH = kagglehub.dataset_download("samaarashidaarbi/dibas-bacterial-colony-dataset")

SOURCES = {"multi": Path(MULTI_PATH), "dibas": Path(DIBAS_PATH)}
CAPS = {"multi": None, "dibas": 30}   # максимум картинок на вид (None = без ограничения)

if not SOURCES["multi"].exists():   # если путь другой — пробуем найти папку 'Bacteria dataset'
    for base in ["/kaggle/input", "/content"]:
        found = list(Path(base).rglob("Bacteria dataset")) if Path(base).exists() else []
        if found:
            SOURCES["multi"] = found[0]
            break
for k, v in SOURCES.items():
    print(k, "->", v, "| существует:", v.exists())
assert SOURCES["multi"].exists(), "Не найден набор Multi-Organism: впишите его путь в MULTI_PATH"
assert SOURCES["dibas"].exists(), "Не найден DIBaS"


def scan_source(name, root, cap):
    by_species = {}
    for p in sorted(root.rglob("*")):
        if p.suffix.lower() not in EXT:
            continue
        sp = p.parent.name
        if any(k in sp.lower() for k in EXCLUDE_KEYS):
            continue
        by_species.setdefault(sp, []).append(p)
    rng = random.Random(SEED)
    rows = []
    for sp, files in sorted(by_species.items()):
        if len(files) > 60:
            print(f"  ! {name}/{sp}: {len(files)} файлов - возможно, это нарезки одних снимков (риск утечки)")
        if cap and len(files) > cap:
            files = rng.sample(files, cap)
        is_pos = int(any(k in sp.lower() for k in POSITIVE_KEYS))
        for f in files:
            rows.append({"path": str(f), "source": name, "species": sp.lower(), "label": is_pos})
    return pd.DataFrame(rows)


DF = pd.concat([scan_source(n, r, CAPS[n]) for n, r in SOURCES.items()], ignore_index=True)
DF["label_name"] = DF["label"].map({1: "E. coli", 0: "Not E. coli"})
print("\nВсего картинок:", len(DF))
print(pd.crosstab([DF["source"], DF["species"]], DF["label_name"]))
print("\nИтого по источникам:")
print(pd.crosstab(DF["source"], DF["label_name"]))
assert DF["label"].sum() > 0, "Не найдено ни одной картинки E. coli - проверьте названия папок и POSITIVE_KEYS"

# ЯЧЕЙКА 3. Проверка данных: кэш картинок, дубликаты, «читерские» признаки, разбиение train/val/test
_k = np.arange(32)[:, None]
_i = np.arange(32)[None, :]
DCT32 = np.cos(np.pi * (2 * _i + 1) * _k / 64)


def phash_bits(img, hash_size=8):
    g = img.convert("L").resize((32, 32), Image.LANCZOS)
    a = np.asarray(g, dtype=np.float64)
    low = (DCT32 @ a @ DCT32.T)[:hash_size, :hash_size].flatten()
    return (low > np.median(low[1:])).astype(np.uint8)


def hamming_matrix(a, b=None):
    a = a.astype(np.int32)
    b = a if b is None else b.astype(np.int32)
    return a @ (1 - b).T + (1 - a) @ b.T


def group_duplicates(bits, thresh):
    n = len(bits)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    dist = hamming_matrix(bits)
    ii, jj = np.where(np.triu(dist <= thresh, k=1))
    for i, j in zip(ii, jj):
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[ri] = rj
    return np.array([find(i) for i in range(n)])


def color_stats(img):
    rgb = np.asarray(img, dtype=np.float32)
    gray = rgb.mean(axis=2)
    lap = (4 * gray[1:-1, 1:-1] - gray[:-2, 1:-1] - gray[2:, 1:-1]
           - gray[1:-1, :-2] - gray[1:-1, 2:])
    b = max(1, gray.shape[0] // 10)
    border = np.concatenate([gray[:b].ravel(), gray[-b:].ravel(), gray[:, :b].ravel(), gray[:, -b:].ravel()])
    return {"mean_r": float(rgb[..., 0].mean()), "mean_g": float(rgb[..., 1].mean()),
            "mean_b": float(rgb[..., 2].mean()), "brightness": float(gray.mean()),
            "contrast": float(gray.std()), "sharpness": float(lap.var()),
            "border_brightness": float(border.mean())}


# --- 3.1 читаем все картинки один раз, приводим к IMG_SIZE и держим в памяти ---
CACHE, HASH, STATS = {}, {}, []
print("Читаю картинки (для больших снимков DIBaS это 1-3 минуты)...")
for n, row in enumerate(DF.itertuples(index=False)):
    try:
        img = Image.open(row.path)
        img.load()
        img = img.convert("RGB")
    except Exception as e:
        print("  битый файл пропущен:", row.path, e)
        continue
    w, h = img.size
    small = img.resize((IMG_SIZE, IMG_SIZE), Image.BILINEAR)
    CACHE[row.path] = small
    HASH[row.path] = phash_bits(small)
    st = color_stats(small)
    st.update(path=row.path, width=w, height=h, file_kb=Path(row.path).stat().st_size / 1024)
    STATS.append(st)
    if (n + 1) % 200 == 0:
        print(f"  обработано {n + 1}/{len(DF)}")

DF = DF[DF["path"].isin(CACHE)].reset_index(drop=True)
DF = DF.merge(pd.DataFrame(STATS), on="path", how="left")
BITS = np.stack([HASH[p] for p in DF["path"]])

# --- 3.2 дубликаты и почти-дубликаты ---
DF["group"] = group_duplicates(BITS, DUP_THRESH)
sizes = DF.groupby("group")["path"].transform("count")
print(f"\nГрупп дубликатов (>1 картинки): {DF.loc[sizes > 1, 'group'].nunique()}, "
      f"картинок в них: {int((sizes > 1).sum())}")

mixed = DF.groupby("group")["label"].nunique()
mixed_groups = list(mixed[mixed > 1].index)
print("Групп с ОБОИМИ классами:", len(mixed_groups))
drop_paths = []
for gid in mixed_groups:
    g = DF[DF["group"] == gid]
    ps = g["path"].tolist()
    a = np.asarray(CACHE[ps[0]], dtype=float)
    dmin = min(np.abs(a - np.asarray(CACHE[q], dtype=float)).mean() for q in ps[1:])
    verdict = "ИДЕНТИЧНЫЕ (ошибка разметки) -> удаляю копию не-E. coli" if dmin < 8 else "разные картинки (ложное срабатывание хэша) -> оставляю"
    print(f"  группа {gid}: {[x.split('/')[-2] for x in ps]} | разница {dmin:.1f} | {verdict}")
    if dmin < 8:
        drop_paths += g.loc[g["label"] == 0, "path"].tolist()
if drop_paths:
    DF = DF[~DF["path"].isin(drop_paths)].reset_index(drop=True)
    BITS = np.stack([HASH[p] for p in DF["path"]])

# --- 3.3 «читерский» тест: можно ли угадать класс по размеру/цвету/яркости/резкости? (отдельно для каждого источника) ---
STAT_COLS = ["width", "height", "mean_r", "mean_g", "mean_b", "brightness", "contrast",
             "sharpness", "border_brightness", "file_kb"]
SHORTCUT_AUC = {}
print("\nAUC модели, которая видит ТОЛЬКО метаданные (0.5 = угадать нельзя, >0.75 = подозрительно):")
for s, g in DF.groupby("source"):
    yv = g["label"].values
    if yv.sum() < 5 or (1 - yv).sum() < 5:
        print("  ", s, ": слишком мало примеров одного из классов, пропуск")
        continue
    try:
        cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SEED)
        pr = cross_val_predict(GradientBoostingClassifier(random_state=SEED), g[STAT_COLS].values, yv,
                               groups=g["group"].values, cv=cv, method="predict_proba")[:, 1]
        SHORTCUT_AUC[s] = float(roc_auc_score(yv, pr))
        print(f"   {s}: AUC = {SHORTCUT_AUC[s]:.3f}")
    except Exception as e:
        print("  ", s, ": не удалось посчитать:", e)

# --- 3.4 разбиение 60/20/20 по ГРУППАМ дубликатов, стратификация по источник+вид ---
strat = (DF["source"] + "/" + DF["species"]).astype("category").cat.codes.values
groups = DF["group"].values
DF["split"] = "train"
s1 = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=SEED)
rest_idx, test_idx = next(s1.split(DF, strat, groups))
s2 = StratifiedGroupKFold(n_splits=4, shuffle=True, random_state=SEED)
_, val_rel = next(s2.split(DF.iloc[rest_idx], strat[rest_idx], groups[rest_idx]))
DF.loc[test_idx, "split"] = "test"
DF.loc[rest_idx[val_rel], "split"] = "val"
assert (DF.groupby("group")["split"].nunique() == 1).all(), "дубликат попал в разные части!"

print("\nРазбиение (строки - источник и класс):")
print(pd.crosstab([DF["source"], DF["label_name"]], DF["split"], margins=True))

# ЯЧЕЙКА 4. Функции: датасет, модель, обучение, калибровка, оценка (только определения, ничего не запускает)
MEAN, STD = [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]

train_tfm = T.Compose([
    T.RandomResizedCrop(IMG_SIZE, scale=(0.6, 1.0), ratio=(0.85, 1.18)),
    T.RandomHorizontalFlip(), T.RandomVerticalFlip(),
    T.RandomApply([T.RandomRotation(90)], p=0.5),
    T.ColorJitter(brightness=0.25, contrast=0.25, saturation=0.15, hue=0.02),
    T.RandomGrayscale(p=0.1),
    T.ToTensor(), T.Normalize(MEAN, STD)])
eval_tfm = T.Compose([T.ToTensor(), T.Normalize(MEAN, STD)])


class CachedDS(Dataset):
    def __init__(self, df, tfm):
        self.paths = df["path"].tolist()
        self.y = df["label"].astype(int).tolist()
        self.tfm = tfm

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, i):
        return self.tfm(CACHE[self.paths[i]]), self.y[i]


def build_model():
    weights = models.ResNet18_Weights.DEFAULT if USE_PRETRAINED else None
    m = models.resnet18(weights=weights)
    m.fc = nn.Linear(m.fc.in_features, 2)
    return m.to(DEVICE)


@torch.no_grad()
def get_logits(model, df, batch_size=32):
    model.eval()
    dl = DataLoader(CachedDS(df, eval_tfm), batch_size=batch_size, shuffle=False, num_workers=0)
    return torch.cat([model(x.to(DEVICE)).cpu() for x, _ in dl]).numpy()


def softmax_T(logits, temperature=1.0):
    z = logits / temperature
    z = z - z.max(axis=1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=1, keepdims=True)


def fit_temperature(logits, y):
    best_t, best_nll = 1.0, 1e9
    for t in np.arange(0.5, 5.01, 0.05):
        p = softmax_T(logits, t)[np.arange(len(y)), y]
        nll = float(-np.log(np.clip(p, 1e-8, 1)).mean())
        if nll < best_nll:
            best_t, best_nll = float(t), nll
    return best_t


def choose_tau(p_ecoli, y, target_acc=0.95, min_coverage=0.80, min_tau=0.70, default=0.80):
    """Порог Uncertain: минимальный tau (не меньше min_tau), при котором точность на «принятых» >= target_acc
    и принято не менее min_coverage картинок. Иначе default."""
    conf = np.maximum(p_ecoli, 1 - p_ecoli)
    pred = (p_ecoli >= 0.5).astype(int)
    for tau in np.arange(min_tau, 0.995, 0.005):
        keep = conf >= tau
        if keep.mean() < min_coverage:
            break
        if (pred[keep] == y[keep]).mean() >= target_acc:
            return float(round(tau, 3))
    return default


def apply_rule(p_ecoli, tau):
    p_ecoli = np.asarray(p_ecoli)
    pred = (p_ecoli >= 0.5).astype(int)
    conf = np.maximum(p_ecoli, 1 - p_ecoli)
    return pred, conf, conf < tau


def train_model(train_df, val_df, epochs_head=6, epochs_ft=6, lr_head=1e-3, lr_ft=3e-5,
                batch_size=16, verbose=True):
    """Сначала учим только последний слой (epochs_head эпох), потом всю сеть с малым lr (epochs_ft эпох).
    Лучшая эпоха выбирается по val (среднее AUC и balanced accuracy). Потом на val подбираются temperature и tau."""
    set_seed(SEED)
    model = build_model()
    dl = DataLoader(CachedDS(train_df, train_tfm), batch_size=batch_size, shuffle=True, num_workers=2,
                    drop_last=len(train_df) >= 2 * batch_size)
    counts = train_df["label"].value_counts().reindex([0, 1]).fillna(1).values.astype(float)
    criterion = nn.CrossEntropyLoss(
        weight=torch.tensor(len(train_df) / (2 * counts), dtype=torch.float32, device=DEVICE))

    def set_backbone_trainable(flag):
        for pname, prm in model.named_parameters():
            prm.requires_grad = bool(flag) or pname.startswith("fc.")

    set_backbone_trainable(False)
    opt = torch.optim.AdamW(model.fc.parameters(), lr=lr_head, weight_decay=1e-4)
    sched = None
    yv = val_df["label"].values.astype(int)
    best_score, best_auc, best_state, history = -1.0, float('nan'), None, []

    for epoch in range(epochs_head + epochs_ft):
        frozen = epoch < epochs_head
        if epoch == epochs_head and epochs_ft > 0:
            set_backbone_trainable(True)
            opt = torch.optim.AdamW(model.parameters(), lr=lr_ft, weight_decay=1e-4)
            sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs_ft)
        model.train()
        if frozen:  # пока backbone заморожен, статистики BatchNorm тоже не трогаем
            for mod in model.modules():
                if isinstance(mod, nn.BatchNorm2d):
                    mod.eval()
        total, seen = 0.0, 0
        for x, y in dl:
            x, y = x.to(DEVICE), y.to(DEVICE)
            opt.zero_grad()
            loss = criterion(model(x), y)
            loss.backward()
            opt.step()
            total += loss.item() * len(y)
            seen += len(y)
        if sched is not None:
            sched.step()
        pv = softmax_T(get_logits(model, val_df))[:, 1]
        auc = roc_auc_score(yv, pv) if len(set(yv)) > 1 else float("nan")
        bacc = balanced_accuracy_score(yv, (pv >= 0.5).astype(int))
        score = ((auc if not np.isnan(auc) else bacc) + bacc) / 2  # и ранжирование, и порог 0.5 должны быть хороши
        history.append({"epoch": epoch + 1, "phase": "head" if frozen else "fine-tune",
                        "train_loss": round(total / max(seen, 1), 4),
                        "val_bal_acc": round(bacc, 3), "val_auc": round(auc, 3)})
        if verbose:
            print(f"  эпоха {epoch + 1:02d} [{history[-1]['phase']}] loss={history[-1]['train_loss']:.3f} "
                  f"val bal.acc={bacc:.3f} val AUC={auc:.3f}")
        if score >= best_score:
            best_score, best_auc = score, auc
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    model.load_state_dict(best_state)
    logits = get_logits(model, val_df)
    temp = fit_temperature(logits, yv)
    pv = softmax_T(logits, temp)[:, 1]
    tau = choose_tau(pv, yv)
    return {"model": model, "T": temp, "tau": tau, "val_score": float(best_score), "val_auc": float(best_auc),
            "history": pd.DataFrame(history)}


def bootstrap_ci(y, pred, fn, n=1000, seed=0):
    rng = np.random.default_rng(seed)
    vals = []
    for _ in range(n):
        idx = rng.integers(0, len(y), len(y))
        if len(set(y[idx])) < 2:
            continue
        vals.append(fn(y[idx], pred[idx]))
    return (round(float(np.percentile(vals, 2.5)), 2), round(float(np.percentile(vals, 97.5)), 2)) if vals else (None, None)


def contact_sheet(paths, captions, thumb=200, cols=4):
    rows = (len(paths) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * thumb, rows * (thumb + 34)), "white")
    draw = ImageDraw.Draw(sheet)
    for i, (p, c) in enumerate(zip(paths, captions)):
        x, y = (i % cols) * thumb, (i // cols) * (thumb + 34)
        sheet.paste(CACHE[p].resize((thumb, thumb)), (x, y))
        draw.text((x + 3, y + thumb + 2), c[:34], fill="black")
        draw.text((x + 3, y + thumb + 16), c[34:68], fill="black")
    return sheet


RESULTS = {}


def evaluate(bundle, df, title, n_show=8):
    df = df.copy().reset_index(drop=True)
    y = df["label"].values.astype(int)
    p = softmax_T(get_logits(bundle["model"], df), bundle["T"])[:, 1]
    pred, conf, unc = apply_rule(p, bundle["tau"])
    df["p_ecoli"], df["pred"], df["confidence"], df["uncertain"] = p, pred, conf, unc
    keep = ~unc
    two = len(set(y)) > 1
    m = {
        "n": len(df), "n_ecoli": int(y.sum()),
        "accuracy": accuracy_score(y, pred),
        "balanced_acc": balanced_accuracy_score(y, pred),
        "precision_ecoli": precision_score(y, pred, zero_division=0),
        "recall_ecoli": recall_score(y, pred, zero_division=0),
        "f1_ecoli": f1_score(y, pred, zero_division=0),
        "roc_auc": roc_auc_score(y, p) if two else float("nan"),
        "pr_auc": average_precision_score(y, p) if two else float("nan"),
        "recall_ci95": bootstrap_ci(y, pred, lambda a, b: recall_score(a, b, zero_division=0)),
        "balanced_acc_ci95": bootstrap_ci(y, pred, balanced_accuracy_score),
        "tau": bundle["tau"], "coverage": float(keep.mean()),
        "ecoli_uncertain": int((unc & (y == 1)).sum()),
        "acc_on_decided": float(accuracy_score(y[keep], pred[keep])) if keep.any() else float("nan"),
        "recall_on_decided": float(recall_score(y[keep], pred[keep], zero_division=0)) if keep.any() else float("nan"),
        "precision_on_decided": float(precision_score(y[keep], pred[keep], zero_division=0)) if keep.any() else float("nan"),
    }
    RESULTS[title] = m
    print(f"\n===== {title}: {m['n']} картинок, из них E. coli: {m['n_ecoli']} =====")
    print(f"Accuracy {m['accuracy']:.3f} | Balanced acc {m['balanced_acc']:.3f} {m['balanced_acc_ci95']} | ROC-AUC {m['roc_auc']:.3f} | PR-AUC {m['pr_auc']:.3f}")
    print(f"E. coli: recall {m['recall_ecoli']:.3f} {m['recall_ci95']} | precision {m['precision_ecoli']:.3f} | F1 {m['f1_ecoli']:.3f}")
    print(f"С правилом Uncertain (tau={m['tau']}): принято {m['coverage']:.0%}, E. coli в Uncertain: {m['ecoli_uncertain']}, "
          f"точность на принятых {m['acc_on_decided']:.3f}, recall на принятых {m['recall_on_decided']:.3f}")
    cm = confusion_matrix(y, pred, labels=[0, 1])
    print(pd.DataFrame(cm, index=["истина: Not E. coli", "истина: E. coli"],
                       columns=["предсказано: Not E. coli", "предсказано: E. coli"]))
    df["correct"] = (df["pred"] == df["label"]).astype(int)
    print("\nПо видам:")
    print(df.groupby("species").agg(n=("path", "count"), accuracy=("correct", "mean"),
                                    mean_p_ecoli=("p_ecoli", "mean"), share_uncertain=("uncertain", "mean")).round(2))
    wrong = df[df["correct"] == 0].sort_values("confidence", ascending=False).head(n_show)
    if len(wrong):
        print("\nСамые уверенные ОШИБКИ:")
        display(contact_sheet(wrong["path"].tolist(),
                              [f"ERR true={r.label} p={r.p_ecoli:.2f} {r.species}" for r in wrong.itertuples()]))
    return df


print("Функции определены.")

# ЯЧЕЙКА 5. Обучение двух вариантов и выбор лучшего по валидации (тест здесь НЕ используется)
train_df = DF[DF["split"] == "train"]
val_df = DF[DF["split"] == "val"]
print("train:", len(train_df), "| val:", len(val_df), "| E. coli в train/val:",
      int(train_df["label"].sum()), "/", int(val_df["label"].sum()))

CONFIGS = {
    "head_only": dict(epochs_head=12, epochs_ft=0),                 # учим только последний слой
    "finetune": dict(epochs_head=3, epochs_ft=9, lr_ft=3e-5),       # потом аккуратно дообучаем всю сеть
}
TRAINED = {}
for cname, cfg in CONFIGS.items():
    print(f"\n=== вариант '{cname}': {cfg}")
    TRAINED[cname] = train_model(train_df, val_df, **cfg)
    b = TRAINED[cname]
    print(f"  -> лучшая эпоха: val AUC = {b['val_auc']:.3f}, итоговый балл = {b['val_score']:.3f}, "
          f"temperature = {b['T']:.2f}, tau (порог Uncertain) = {b['tau']}")

BEST_NAME = max(TRAINED, key=lambda k: TRAINED[k]["val_score"])
BUNDLE = TRAINED[BEST_NAME]
print(f"\nВыбран вариант: {BEST_NAME} (val AUC {BUNDLE['val_auc']:.3f}, балл {BUNDLE['val_score']:.3f})")
print(BUNDLE["history"].to_string(index=False))

print("DF" in globals(), "BUNDLE" in globals())

# ЯЧЕЙКА 6. Финальная оценка на TEST (запускать один раз, когда модель уже выбрана)
_missing = [n for n in ["DF", "BUNDLE", "CACHE", "evaluate"] if n not in globals()]
if _missing:
    raise RuntimeError(f"Нет переменных {_missing}: Colab перезапустился и всё забыл. "
                           "Запустите заново ячейки 1, 2, 3, 4, 5 по порядку, потом эту.")

    test_df = DF[DF["split"] == "test"]
    PRED_TEST = evaluate(BUNDLE, test_df, "TEST: оба источника")
    for _s in sorted(test_df["source"].unique()):
     _ = evaluate(BUNDLE, test_df[test_df["source"] == _s], f"TEST: только {_s}", n_show=4)

# ЯЧЕЙКА 7. Независимая проверка: учим ТОЛЬКО на multi, проверяем на DIBaS (модель его не видела)

multi = DF[DF["source"] == "multi"]

dibas = DF[DF["source"] == "dibas"]

x_train = multi[multi["split"] != "val"]

x_val = multi[multi["split"] == "val"]

idx_m = np.where(DF["source"].values == "multi")[0]

idx_d = np.where(DF["source"].values == "dibas")[0]

dmin = hamming_matrix(BITS[idx_d], BITS[idx_m]).min(axis=1)

print(f"Картинок DIBaS, похожих на картинки multi (Хэмминг <= {DUP_THRESH}): {int((dmin <= DUP_THRESH).sum())} из {len(idx_d)}")

print("(если число большое - наборы пересекаются и проверка не независима)\n")

print("Обучение на multi:", len(x_train), "картинок, E. coli:", int(x_train["label"].sum()))

BUNDLE_X = train_model(x_train, x_val, **CONFIGS[BEST_NAME])

PRED_EXT = evaluate(BUNDLE_X, dibas, "ВНЕШНИЙ: DIBaS (обучение только на multi)")

print("\nСравнение доменов (средние значения по источникам):")

print(DF.groupby("source")[["width", "height", "brightness", "contrast", "sharpness", "border_brightness"]].mean().round(1))

# ЯЧЕЙКА 8. Итоговая программа: картинка -> E. coli / Not E. coli / Uncertain + интерфейс
@torch.no_grad()
def predict_image(img, bundle=None):
    bundle = bundle or BUNDLE
    img = img.convert("RGB")
    if min(img.size) < 96:
        return {"prediction": "Uncertain", "confidence": None, "status": "Uncertain",
                "message": "Изображение слишком маленькое (меньше 96 px по короткой стороне)."}
    x = eval_tfm(img.resize((IMG_SIZE, IMG_SIZE), Image.BILINEAR)).unsqueeze(0).to(DEVICE)
    bundle["model"].eval()
    p = float(softmax_T(bundle["model"](x).cpu().numpy(), bundle["T"])[0, 1])
    conf = max(p, 1 - p)
    if conf < bundle["tau"]:
        return {"prediction": "Uncertain", "confidence": conf, "status": "Uncertain",
                "message": (f"Модель не уверена (уверенность {conf:.0%} ниже порога {bundle['tau']:.0%}). "
                            "Возможно, изображение отличается от обучающих (увеличение, окраска, фон) - нужна проверка человеком.")}
    return {"prediction": "E. coli" if p >= 0.5 else "Not E. coli", "confidence": conf, "status": "Result",
            "message": "Исследовательский прототип, не диагностический инструмент."}


# демонстрация на случайных картинках из test
demo_rows = DF[DF["split"] == "test"].sample(8, random_state=SEED)
caps, ps = [], []
for r in demo_rows.itertuples():
    out = predict_image(Image.open(r.path))
    conf = "-" if out["confidence"] is None else f"{out['confidence']:.0%}"
    caps.append(f"{out['prediction']} {conf} | истина: {r.label_name}")
    ps.append(r.path)
    print(f"{r.species:38s} истина: {r.label_name:12s} -> {out['prediction']:12s} ({conf})")
display(contact_sheet(ps, caps))

# интерфейс (Gradio): в Colab появится публичная ссылка
import gradio as gr


def ui_predict(image):
    if image is None:
        return "-", "-", "-", "Загрузите изображение."
    out = predict_image(image)
    conf = "-" if out["confidence"] is None else f"{out['confidence']:.0%}"
    return out["prediction"], conf, out["status"], out["message"]


demo = gr.Interface(
    fn=ui_predict,
    inputs=gr.Image(type="pil", label="Микроскопическое изображение бактерий"),
    outputs=[gr.Textbox(label="Prediction"), gr.Textbox(label="Confidence"),
             gr.Textbox(label="Status (Result / Uncertain)"), gr.Textbox(label="Comment")],
    title="E. coli / Not E. coli / Uncertain - исследовательский прототип",
    description="Загрузите изображение (оптическая микроскопия). Учебный прототип, не диагностическая система.")
demo.launch(share=True)

# ЯЧЕЙКА 9. Сводка чисел для README и сохранение результатов (скачается zip)

cols = ["n", "n_ecoli", "accuracy", "balanced_acc", "recall_ecoli", "precision_ecoli", "f1_ecoli",

"roc_auc", "pr_auc", "coverage", "ecoli_uncertain", "acc_on_decided"]

summary = pd.DataFrame(RESULTS).T[cols].astype({"n": int, "n_ecoli": int, "ecoli_uncertain": int})

summary = summary.apply(lambda c: c.round(3) if c.dtype == float else c)

print(summary.to_string())

print("\nШорткат-AUC по метаданным:", {k: round(v, 3) for k, v in SHORTCUT_AUC.items()})

print("Выбранный вариант обучения:", BEST_NAME, "| temperature:", round(BUNDLE["T"], 2), "| tau:", BUNDLE["tau"])

Path("outputs").mkdir(exist_ok=True)

torch.save(BUNDLE["model"].state_dict(), "outputs/model.pt")

json.dump({"arch": "resnet18", "img_size": IMG_SIZE, "temperature": BUNDLE["T"], "tau": BUNDLE["tau"],

"variant": BEST_NAME}, open("outputs/meta.json", "w"), indent=2)

summary.to_csv("outputs/results.csv")

DF.drop(columns=["label_name"]).to_csv("outputs/manifest.csv", index=False)

if "PRED_TEST" in globals():
  PRED_TEST.to_csv("outputs/predictions_test.csv", index=False)

if "PRED_EXT" in globals():
  PRED_EXT.to_csv("outputs/predictions_external.csv", index=False)

shutil.make_archive("ecoli_results", "zip", "outputs")
try:
  from google.colab import files
  files.download("ecoli_results.zip")
except ImportError:
  print("Архив: ecoli_results.zip")

from google.colab import files
up = files.upload()   # выберите cell10_docs.py
exec(open(list(up)[0], encoding="utf-8").read())